version: '3'
services:
  db:
    image: mysql:5.7
    ports: 
      - 127.0.0.1:3307:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      # - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootstark
      MYSQL_DATABASE: stark
      MYSQL_USER: stark
      MYSQL_PASSWORD: stark
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: stark
      WORDPRESS_DB_PASSWORD: stark
      WORDPRESS_DB_NAME: stark
volumes:
  db_data: {}